# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://localhost:8000/posts
Accept: application/json
###
GET http://localhost:8000/users
Accept: application/json

###
GET http://localhost:8000/user/me
Accept: application/json


###
GET http://localhost:8000/posts
Accept: application/json


